### ISSUE TITLE
1.5.2 Integration update not connecting to inverter

### ISSUE THREAD

**Issue by yurix2019** [Pho3niX90/solis_modbus#77]
I just installed the latest version of the integration and there is now no data coming from my inverter. I’ve tried reloading the integration many times and it reloads quickly with the same null response.

Here's the error log. 

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 06:44:57 (7 occurrences)
Last logged: 07:42:37

Error setting up entry Solis: 192.168.0.107 for solis_modbus
Traceback (most recent call last):
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 25, in connect
    raise _LOGGER.warning(
TypeError: exceptions must derive from BaseException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solis_modbus/__init__.py", line 65, in async_setup_entry
    await controller.connect()
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 32, in connect
    raise _LOGGER.error(f"Failed to connect to Modbus device. Will retry")
TypeError: exceptions must derive from BaseException

**Comment by Pho3niX90** [comment]
reverted the problematic code in 1.5.3 until it can be tested.

**Comment by yurix2019** [comment]
Many thanks.
