### ISSUE TITLE
Errors in Logs after updating again

### ISSUE THREAD

**Issue by miketarg** [Pho3niX90/solis_modbus#79]
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 3:20:22 PM (2 occurrences)
Last logged: 3:21:47 PM

Error setting up entry Solis: 192.168.0.83 for solis_modbus
Traceback (most recent call last):
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 25, in connect
    raise _LOGGER.warning(
TypeError: exceptions must derive from BaseException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solis_modbus/__init__.py", line 65, in async_setup_entry
    await controller.connect()
  File "/config/custom_components/solis_modbus/modbus_controller.py", line 32, in connect
    raise _LOGGER.error(f"Failed to connect to Modbus device. Will retry")
TypeError: exceptions must derive from BaseException

Updated as the last ticket was closed as fixed but I am getting errors again and my inverter wont connect to HA.

**Comment by miketarg** [comment]
Hello, can you please take a look at this as I tried updating as you mentiond this had been fixed but it appears to be causing issues still, please can you let me know if you need any other information?

**Comment by Pho3niX90** [comment]
Will delve more deeply into this for the next version. The one released today should be better already
